name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]  # 只在推送到 main 分支时触发
    paths: [ '**.py' ]  # 只有 Python 文件变化时才触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 运行器，因为要生成 EXE

    steps:
    - uses: actions/checkout@v4  # 检出代码
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # 使用你项目所需的 Python 版本
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt  # 如果有其他依赖
        
    - name: Run PyInstaller
      run: |
        pyinstaller UImain.spec
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: executable
          path: dist/  # PyInstaller 默认输出目录